config/routes.rb
Rails.application.routes.draw do
  root 'recipes#index'
  resources :recipes
  resources :ingredients
  resources :recipe_types
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe
  validates :list, presence: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
 has_many :ingredients
 has_one :recipe_type
 validates :name, presence: true, uniqueness: true, length: {minimum: 5}
end

app/models/recipe_type.rb
class RecipeType < ApplicationRecord
  belongs_to :recipe
  validates :recipe_type, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_recipe, only: %i[show edit update destroy]

  def show
  end

  def index
    @ingredients = Ingredient.all
  end

  def new
    @ingredient = Ingredient.new
    @recipe = Recipe.find(params[:recipe_id])
  end

  def edit
  end

  def create
    @ingredient = Ingredient.new(ing_params)
    if @ingredient.save
      flash[:notice] = "ingredient was successfully Added."
      redirect_to recipe_path(@ingredient.recipe)
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def update
    if @ingredient.update(ing_params)
      flash[:notice] = "ingredient edited successfully."
      redirect_to recipe_path(@ingredient.recipe)
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
      @ingredient.destroy
      flash[:notice] = "The recipe was deleted."
      redirect_to recipes_path
  end


  private

  def set_recipe
    @ingredient = Ingredient.find(params[:id])
  end

  def ing_params
    params.require(:ingredient).permit(:list, :recipe_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/recipe_types_controller.rb
class RecipeTypesController < ApplicationController
    before_action :set_recipe_type, only: %i[show edit update destroy]

    def show
    end

    def index
      @recipe_types = RecipeType.all
    end

    def new
      @recipe_type = RecipeType.new
      @recipe = Recipe.find(params[:recipe_id])
    end

    def edit
    end

    def create
      @recipe_type = RecipeType.new(rt_params)
      if @recipe_type.save
        flash[:notice] = "Recipe type was successfully Added."
        redirect_to recipe_path(@recipe_type.recipe)
      else
        render 'new', status: :unprocessable_entity
      end
    end

    def update
      if @recipe_type.update(rt_params)
        flash[:notice] = "Recipe type edited successfully."
        redirect_to recipe_path(@recipe_type.recipe)
      else
        render 'edit', status: :unprocessable_entity
      end
    end

    def destroy
        @recipe_type.destroy
        flash[:notice] = "The recipe type was deleted."
        redirect_to recipes_path
    end

    private

    def set_recipe_type
      @recipe_type = RecipeType.find(params[:id])
    end

    def rt_params
      params.require(:recipe_type).permit(:recipe_type, :recipe_id)
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[show edit update destroy]

  def show
  end

  def index
    @recipes = Recipe.all
  end

  def new
    @recipe = Recipe.new
  end

  def edit
  end

  def create
    @recipe = Recipe.new(recipe_params)
    if @recipe.save
      flash[:notice] = "Recipe was successfully Added."
      redirect_to recipes_path
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def update
    if @recipe.update(recipe_params)
      flash[:notice] = "Recipe was edited successfully."
      redirect_to @recipe
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
      @recipe.destroy
      flash[:notice] = "The recipe was deleted."
      redirect_to recipes_path
  end

  private

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/ingredients/edit.html.erb
<h1>Edit the ingredient: </h1>
<%= render 'shared/errors', obj: @ingredient%>
<%=form_with(model: @ingredient, local: true) do |f|%>
  <%=f.label :ingredients%>
  <%=f.text_area :list%>
  <%=f.submit%>
<%end%>

app/views/ingredients/new.html.erb
<%= render 'shared/errors', obj: @ingredient%>
 <%id = params[:recipe_id]%>
<h1>Adding new ingredient:</h1>
<%= form_for @ingredient do |f| %>
  <%= f.label :ingredients%>
  <%= f.text_area :list%>
  <%= f.hidden_field :recipe_id, value: id%>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstTest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% flash.each do |name, msg| %>
    <%=msg%>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Starting now!</h1>

app/views/recipe_types/edit.html.erb
<h1>Edit the recipe type: </h1>
<%= render 'shared/errors', obj: @recipe_type%>
<%=form_with(model: @recipe_type, local: true) do |f|%>
  <%=f.label :Recipe_type%>
  <%=f.text_field :recipe_type%>
  <%=f.submit%>
<%end%>

app/views/recipe_types/new.html.erb
<%= render 'shared/errors', obj: @recipe_type%>
<h1>Adding the recipe type:</h1>
<%=form_with(model: @recipe_type, local: true) do |f|%>
  <%=f.label :Recipe_type%>
  <%=f.text_field :recipe_type%>
  <%=f.hidden_field :recipe_id, value: params[:recipe_id]%>
  <%=f.submit%>
<%end%>

app/views/recipes/edit.html.erb
<%= render 'shared/errors', obj: @recipe%>
<h1>Editing the recipe: <%= @recipe.name%></h1>
<%=form_with(model: @recipe, local: true) do |f|%>
  <%=f.label :Recipe_name%>
  <%=f.text_field :name%>
  <%=f.submit%>
<%end%>

app/views/recipes/index.html.erb
<h1>
  All recipes |
  <%= link_to 'Add new recipe', new_recipe_path%>
</h1>
<ul>
  <%@recipes.each do |r|%>
    <li><b>Recipe name: </b><%=link_to r.name, recipe_path(r)%></li>
    <% if r.ingredients.any?%>
      <b><u>Ingredients: </u></b>
      <%r.ingredients.each do |ing|%>
        <li><%= ing.list%></li>
      <% end %>
      <%= link_to 'add another ingredient', new_ingredient_path(recipe_id: r.id)%>
    <% else%>
      <li><%= link_to 'add ingredients', new_ingredient_path(recipe_id: r.id)%></li>
    <%end%>
    <% if r.recipe_type.nil?%>
      <li><%= link_to 'add recipe type', new_recipe_type_path(recipe_id: r.id)%></li></br>
    <% else%>
      <%rt = RecipeType.find_by(recipe_id: r.id)%>
      <li><b>Recipe type: </b><%= rt.recipe_type%></li></br>
    <%end%>
  <%end%>
</ul>

app/views/recipes/new.html.erb
<h1>Adding new recipe:</h1>
<%=form_with(model: @recipe, local: true) do |f|%>
  <%=f.label :name%>
  <%=f.text_field :name%>
  <%=f.submit%>
<%end%>

app/views/recipes/show.html.erb
<h1>Showing recipe details</h1>
<ul>
  <li><strong>Recipe name: <%= link_to @recipe.name, edit_recipe_path(@recipe.id)%></<strong></li>
  <%if @recipe.ingredients.any?%>
  <strong><u>Ingredients: </u></strong>
    <%@recipe.ingredients.each do |ing|%>
      <li><strong><%= link_to ing.list, edit_ingredient_path(ing.id)%></<strong></li>
    <% end %>
  <% else %>
    <li><strong>Ingredients: <%= link_to 'add ingredient', new_ingredient_path(recipe_id: @recipe.id)%></<strong></li>
  <% end %>

  <%if @recipe.recipe_type.nil?%>
  <li><strong>Recipe type: <%= link_to 'add recipe type', new_recipe_type_path(recipe_id: @recipe.id)%></<strong></li>
  <% else %>
    <%rt = RecipeType.find_by(recipe_id: @recipe.id)%>
    <li><strong>Recipe type: <%= link_to rt.recipe_type, edit_recipe_type_path(rt.id)%></<strong></li>
  <% end %>
</ul>
<h2>
  <%= link_to 'delete recipe', recipe_path, data: {turbo_confirm: "Are you sure?", turbo_method: :delete}%>
</h2>

app/views/shared/_errors.html.erb
<%if obj.errors.any?%>
  <h1>The following errors prevented the <%= obj.class.name.downcase %> from being saved</h1>
 <% obj.errors.full_messages.each do |err|%>
  <li><%=err%></li>
 <% end%>
<% end %>